### ISSUE TITLE
Afficher animations en cours et à venir en priorité

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-event-reservation#12]
Sur la liste des animations pour les admins les animations sont affichées ordonnées par date, des plus anciennes aux plus récentes.

![Capture d’écran du 2023-06-29 10-54-16](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/15977920/4311153f-d7e9-451c-bfdf-3036d9efbcf4)

Les anciennes animations apparaissent en premier ce qui peut pousser les animations de la saison en cours sur les dernières pages.

On pourrait cacher les animations passées par défaut avec l'option de les afficher dans les paramètres de recherche.

**Comment by amandine-sahl** [comment]
En lien avec l'issue #10 et la PR #11 

L'idée était plutôt de jouer sur les filtres par défaut

**Comment by mdartic** [comment]
Je te rejoins @amandine-sahl 

Il manque probablement le choix du tri (que tu avais avant).

En l'état, je considère que seule la partie tri est à faire, si ta PR venait à être mergée.
