### ISSUE TITLE
Erreur 500 à confirmation réservation sur animation sans capacité

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-event-reservation#13]
Erreur de programmation dans la vue backend `confirm_reservation` si l'événement n'a pas de capacité renseignée côté Geotrek.

C'est un 1-line fix ici : https://github.com/GeotrekCE/Geotrek-event-reservation/blob/3d5effe664b849c4c9d5a398f6a660260693371c/backend/core/routes.py#L358C11-L358C11

Le comportement que j'ai commencé à implémenter dans ce cas est qu'il n'y a pas de limite de place.

**Comment by amandine-sahl** [comment]
C'est en lien avec l'ajout du champ reservable oui/non dans Geotrek. Il faudrait pour les cas où l'animation n'est pas réservable bloquer le processus d'inscription et pour les autres effectivement pas de limite.
