### ISSUE TITLE
Msg erreur sur annulation d'un évènement

### ISSUE THREAD

**Issue by aferchal** [GeotrekCE/Geotrek-event-reservation#19]
Test sur l'annulation d'une animation : mail d'annulation bien reçu mais msg d'erreur sur l'interface : `Une erreur est survenue :
TypeError: NetworkError when attempting to fetch resource.`

Clic sur bouton "Dé annuler" non opérationnel

![image](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/39522029/23714502-098b-488f-b642-2e1297306fe2)

**Comment by mdartic** [comment]
Est ce que le message d'erreur s'affiche lors de l'annulation ? Ou lors du clic sur "dé annuler" ?

Est ce qu'il y a une trace côté backend précisant l'erreur qui a eu lieu ?

**Comment by marcantoinedupre** [comment]
Note : par défaut les erreurs du backend se retrouvent dans le fichier `./log/png-web/png-resa.log` (par rapport au répertoire du fichier `docker-compose.yml`). Les logs sont datés pour retrouver les choses intéressantes. La stacktrace d'une erreur nous est particulièrement utile. Exemple de stacktrace dans les logs :

```
ERROR 2023-06-30 15:00:30,085 app Exception on /send-login-email [POST]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/png-resa/core/routes.py", line 449, in send_login_email
    raise Exception("test Marc-Antoine")
Exception: test Marc-Antoine
INFO 2023-06-30 15:01:37,336 core.utils Email envoyé "[Rando Guadeloupe] Lien de connexion sur site de réservation du PNG" à ['admin@example.com']
INFO 2023-06-30 15:24:30,183 core.utils Email envoyé "[Rando Guadeloupe] Lien de connexion sur site de réservation du PNG" à ['admin@example.com']
INFO 2023-06-30 15:42:54,969 core.utils Email envoyé "[Rando Guadeloupe] Votre réservation est confirmée" à ['foo@example.com']
```

**Comment by aferchal** [comment]
On vient de tester sur le changement de statut d'un inscrit (passer de liste d'attente à confirmer), sur un évènement non publié. On a ce meme msg d'erreur. En publiant sur geotrek et en refaisant la manip, le msg ne s'affiche pas. Donc effectivement msg d'erreur très probablement en lien avec le non publié.
