### ISSUE TITLE
Pas de mail d'annulation envoyé suite à annulation par admin d'un participant

### ISSUE THREAD

**Issue by aferchal** [GeotrekCE/Geotrek-event-reservation#23]

**Comment by amandine-sahl** [comment]
Je n'ai pas eu le soucis de mon coté. Je reçoit bien le message.

**Comment by marcantoinedupre** [comment]
En effet il n'y a pas d'envoi de mail d'annulation si c'est l'admin qui annule une réservation. L'idée était que l'admin annule la réservation en concertation ou à la demande du participant qui n'a donc pas besoin d'être averti.

J'ajoute l'envoi d'un mail de confirmation de l'annulation dans ce cas ? Avec le même template que quand c'est la personne inscrite qui déclenche l'annulation ?

```
<h1>Confirmation d'annulation de votre réservation pour {{ event.name }}</h1>

<p>Nous vous confirmons avoir pris en compte l'annulation de votre réservation pour <strong>{{ reservation.nb_places }}
    personnes</strong> pour l'événement <strong>{{ event.name }}</strong> ayant lieu le
    {{ event.begin_date|format_date }}.</p>

<p>Merci de nous avoir prévenu !</p>
```

**Comment by aferchal** [comment]
Je pense au cas de figure qui peut se présenter à cette période de l'année en Guadeloupe, à saovir des conditions climatiques particulières qui ne permettent pas à de tenir l'évènement en extérieur. Dans ce cas l'admin annule la réservation et le mail auto serait dans ce cas intéressant. Je vois avec Joël pour confimration

**Comment by marcantoinedupre** [comment]
OK dans ce cas on parle plutôt de l'annulation de l'événement, c'est bien ça ? Si un admin annule l'événement sur le portail de réservation (après l'avoir annulé dans Geotrek) un mail est bien envoyé à chacun des inscrits.

**Comment by aferchal** [comment]
ok autant pour moi, on est bon comme ça. Ticket à cloturer
