### ISSUE TITLE
Personnalisation frontend

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-event-reservation#24]
Afin de personnaliser l'interface de réservation (logo page, titre page, couleur arrière-plan bandeau, favicon, title), il serait intéressant de pouvoir renseigner des variables. En l'état, c'est assez compliqué d'appliquer ces modifications.

Le fichier 'config.js' devant déjà être modifié pour la configuration de base, ne pourrait-il pas contenir ces informations ? Voir même aussi prévoir une variable vers un 'custom.css' ?

**Comment by amandine-sahl** [comment]
Tu pourrais nous transmettre toutes les modifications que tu as réalisé pour que l'on puisse les transformer en configuration?

**Comment by noelmartinon** [comment]
C'est du bricolage mais, dans l'urgence de mise en prod et sans trop toucher la sortie 'dist' ni maîtrise des sources Node.js, j'ai fait ça à partir de la racine du site : 

Création arborescence 'custom' : 
```
mkdir -p custom/css custom/js custom/images
```

Fichier CSS pour couleur bandeau entête (=color text boutons aussi) et boutons hover : 
```
cat <<EOF > custom/css/custom.css
.bg-sky-500 {
  --tw-bg-opacity: 1;
  background-color: #EC008C;
}
:root {
  --blue-800: #822854;
}
EOF
```

Remplacement 'logo.svg' et 'favicon.ico' par liens symboliques (possible utiliser 'cp') : 
```
ln -sf ${PWD}/custom/images/logo.svg ./assets/logo.svg
ln -sf ${PWD}/custom/images/favicon.ico ./favicon.ico
```
Modification de index.html (lang, title, ajout custom.css) : 
```
sed -i 's/lang="en"/lang="fr"/' index.html
sed -i 's/Vite App/PNG - Réservation des animations/' index.html
sed -i '/config.js/a \ \ \ \ <link rel="stylesheet" href="/custom/css/custom.css">' index.html
```

J'ai essayé d'ajouter un code javascript dans 'config.js' pour changer la classe du tag 'header' afin d'appliquer un style personnalisé mais j'ai abandonné l'idée car je reste sur un 'undefined' avec ```document.getElementsByTagName('header')[0]```.
