### ISSUE TITLE
Bloquer le formulaire d'annulation si l'animation n'est pas annulée dans Geotrek

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-event-reservation#25]
Pour éviter les risques de confusion, il serait interressant de bloquer le formulaire d'annulation tant que l'animation n'est pas réellement annulée dans Geotrek

**Comment by marcantoinedupre** [comment]
Le formulaire n'est pas bloqué mais il y a une erreur à l'envoi que l'animation ne peut être annulée sur le portail de réservation car elle n'est pas annulée dans Geotrek.

Mais ce serait mieux niveau UI/UX si le formulaire était désactivé dès l'arrivée sur les infos de l'événement, c'est peut-être ça que tu veux dire ?

**Comment by amandine-sahl** [comment]
> Mais ce serait mieux niveau UI/UX si le formulaire était désactivé dès l'arrivée sur les infos de l'événement, c'est peut-être ça que tu veux dire ?

Effectivement je parlais du front
Pour le moment ça donne ça

![image](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/3088650/ae0be395-bbf3-4218-ace3-6a2a1e6ff5fa)
