### ISSUE TITLE
Remplacer valeurs booléennes par « Oui/Non » sur détails Événement

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-event-reservation#3]
Des valeurs booléennes true/false apparaîssent sur le composant détails d'un événement :

![image](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/15977920/fefb44e9-c5a6-42bf-bedf-00bf0cbf18e0)

À remplacer par Oui ou Non.

**Comment by mdartic** [comment]
Corrigé sur la branche pn-guadeloupe (cf commit).

Démo http://png-resa-demo.geotrek.fr à jour.

**Comment by mdartic** [comment]
![image](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/2027964/08b1913f-f7b3-447b-bdcf-b56e7ee4bdb1)

(résultat actuel pour page d'admin)

**Comment by mdartic** [comment]
@aferchal est ce que l'anomalie est corrigée de manière correcte ? 

Si OK, je clôture le ticket.
