### ISSUE TITLE
Masquer formulaire inscription si non réservable

### ISSUE THREAD

**Issue by noelmartinon** [GeotrekCE/Geotrek-event-reservation#32]
En complément du #22, lorsque l'animation est non réservable,  il faudrait que l'accès au formulaire soit remplacé par un message "Aucune inscription n'est nécessaire pour cette animation".

**Comment by amandine-sahl** [comment]
Pour le moment le formulaire est bloqué et le message est ''Animation sans réservation" mais on peut changer le texte
