### ISSUE TITLE
Ajouter un ctrl de validité sur champ téléphone

### ISSUE THREAD

**Issue by aferchal** [GeotrekCE/Geotrek-event-reservation#4]
Ajouter un crtl de validité pour le champ téléphone sur le formulaire d'inscription à un évènement (doit correspondre à 10 chiffres)

**Comment by mdartic** [comment]
Attention, si des utilisateurs internationaux veulent mettre leur numéro, la règle de 10 chiffres ne marchera pas.

Les validations côté front utilisent la bibliothèque [`yup`](https://github.com/jquense/yup), et il existe une extension pour les numéros de téléphone : 

https://yup-phone.js.org/

À voir si pertinent, pour de l'international.

Sinon, il est possible de préciser à `yup` que le téléphone doit être sur 10 caractères : 

https://github.com/jquense/yup#stringlengthlimit-number--ref-message-string--function-schema

**Comment by aferchal** [comment]
Il est prévu un phoning donc le n° de tel doit etre exact. Je serai partant pour mettre sur 10 chiffres car on sécurise la majorité des inscriptions. Le champ commentaire peut éventuellement servir si souci d'inscription

**Comment by aferchal** [comment]
Vu avec Joël on part sur 10 caractères car c 99,9% des inscriptions

**Comment by camillemonchicourt** [comment]
OK idéalement en faire un paramètre, comme ça un autre déploiement pourrait mettre une autre valeur, voire laisser le paramètre vide et dans ce cas ne pas vérifier la longueur du champs.
