### ISSUE TITLE
Modification du msg d'erreur si liste d'attente > 10 sur un évèneent

### ISSUE THREAD

**Issue by aferchal** [GeotrekCE/Geotrek-event-reservation#40]
Suite au choix de limiter les inscriptions au dela de 10 personnes en liste d'attente, le msg affiché est ambigüe :

![image](https://github.com/GeotrekCE/Geotrek-event-reservation/assets/39522029/2422c469-01a4-4e7c-8ac5-573c16537f9a)

A t'on la possibilté de le modifier pour éviter le terme qu'apparaisse le terme Erreur. Un msg du style : "Le quota du  nombre de personnes en liste d'attente est atteint sur cet événèment. Réservation ou placement sur liste d'attente impossible, l'évènement est complet. Vous pouvez prendre contact avec le Parc pour de plus amples renseignements"

A voir aussi si possible de mettre ce paramètre en variable

**Comment by amandine-sahl** [comment]
Globalement les messages d'erreur ne sont pas très clair et ne sont pas compris par les utilisateurs

**Comment by amandine-sahl** [comment]
Normalement avec les messages via toast c'est plus clair
