### ISSUE TITLE
[Backend]Ne pas envoyer le mail annulation à l'ensemble des admins

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-event-reservation#46]
Nous avons beaucoup d'administrateurs, car les intervenants peuvent se connecter pour récupérer la liste des participants. A chaque annulation tout le monde reçoit un mail.

A voir : ajouter un paramètre spécifiant les mails recevant les messages d'annulation

**Comment by aferchal** [comment]
De notre côté, envoi manuel du fichier export aux prestataires donc pas ce pb la. En lien avec le ticket #54
