### ISSUE TITLE
Ouvrir dans un nouvel onglet la page d'inscription à une animation

### ISSUE THREAD

**Issue by aferchal** [GeotrekCE/Geotrek-event-reservation#52]
Ajouter l'attribut `target="_blank"` sur le bouton `S'inscrire à l'évenement` pour conserver les tris éventuellement faits dans Geotrek Rando et pouvoir revenir dessus facilement

**Comment by noelmartinon** [comment]
Il faut ajouter la ligne suivante à la ligne 59 de 'scriptsFooter.html' :
`target: "_blank",`
